// Reminder: Modify typemap.dat to customize the header file generated by wsdl2h
/* pif.h
   Generated by wsdl2h 2.8.132 from pif.wsdl and typemap.dat
   2026-04-20 09:40:58 GMT

   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE.

gSOAP XML Web services tools
Copyright (C) 2000-2023, Robert van Engelen, Genivia Inc. All Rights Reserved.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

/**

@page page_notes Notes

@note HINTS:
 - Run soapcpp2 on pif.h to generate the SOAP/XML processing logic:
   Use soapcpp2 -I to specify paths for #import
   Use soapcpp2 -j to generate improved proxy and server classes.
   Use soapcpp2 -r to generate a report.
 - Edit 'typemap.dat' to control namespace bindings and type mappings:
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Run Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -c to generate pure C code.
 - Use wsdl2h -R to include the REST operations defined by the WSDLs.
 - Use wsdl2h -O3 or -O4 to optimize by removing unused schema components.
 - Use wsdl2h -d to enable DOM support for xsd:any and xsd:anyType.
 - Use wsdl2h -F to simulate struct-type derivation in C (also works in C++).
 - Use wsdl2h -f to generate flat C++ class hierarchy, removes type derivation.
 - Use wsdl2h -g to generate top-level root elements with readers and writers.
 - Use wsdl2h -U to map XML names to C++ Unicode identifiers instead of _xNNNN.
 - Use wsdl2h -u to disable the generation of unions.
 - Use wsdl2h -L to remove this @note and all other @note comments.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE GENERATED soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2023, Robert van Engelen, Genivia Inc. All Rights Reserved.
The wsdl2h tool and its generated software are released under the GPL.
This software is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt c,w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://tempuri.org/ns.xsd                                                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * $SIZE typemap variable:                                                    *
 *   int                                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to 'typemap.dat' then rerun wsdl2h (use wsdl2h -t typemap.dat):

ns1 = "http://tempuri.org/ns.xsd"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://tempuri.org/ns.xsd"
//gsoap ns1   schema namespace:	http://tempuri.org/ns.xsd
//gsoap ns1   schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/

/// Built-in type "xs:base64Binary".
struct xsd__base64Binary
{
    unsigned char *__ptr;
    int __size;
    char *id, *type, *options; // NOTE: non-NULL for DIME/MIME/MTOM XOP attachments only
};



/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://tempuri.org/ns.xsd                                                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://tempuri.org/ns.xsd                                                *
 *                                                                            *
\******************************************************************************/

/// @brief "http://tempuri.org/ns.xsd":byeRequest is a complexType.
///
/// @note struct ns__byeRequest operations:
/// - ns__byeRequest* soap_new_ns__byeRequest(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default_ns__byeRequest(struct soap*, ns__byeRequest*) default initialize members
/// - int soap_read_ns__byeRequest(struct soap*, ns__byeRequest*) deserialize from a source
/// - int soap_write_ns__byeRequest(struct soap*, ns__byeRequest*) serialize to a sink
/// - ns__byeRequest* soap_dup_ns__byeRequest(struct soap*, ns__byeRequest* dst, ns__byeRequest *src) returns deep copy of ns__byeRequest src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del_ns__byeRequest(ns__byeRequest*) deep deletes ns__byeRequest data members, use only on dst after soap_dup_ns__byeRequest(NULL, ns__byeRequest *dst, ns__byeRequest *src) (use soapcpp2 -Ed)
struct ns__byeRequest
{
/// Element "id" of type xs:int.
    int                                  id                             1;	///< Required element.
};

/// @brief "http://tempuri.org/ns.xsd":applyFilterResponse is a complexType.
///
/// @note struct ns__applyFilterResponse operations:
/// - ns__applyFilterResponse* soap_new_ns__applyFilterResponse(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default_ns__applyFilterResponse(struct soap*, ns__applyFilterResponse*) default initialize members
/// - int soap_read_ns__applyFilterResponse(struct soap*, ns__applyFilterResponse*) deserialize from a source
/// - int soap_write_ns__applyFilterResponse(struct soap*, ns__applyFilterResponse*) serialize to a sink
/// - ns__applyFilterResponse* soap_dup_ns__applyFilterResponse(struct soap*, ns__applyFilterResponse* dst, ns__applyFilterResponse *src) returns deep copy of ns__applyFilterResponse src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del_ns__applyFilterResponse(ns__applyFilterResponse*) deep deletes ns__applyFilterResponse data members, use only on dst after soap_dup_ns__applyFilterResponse(NULL, ns__applyFilterResponse *dst, ns__applyFilterResponse *src) (use soapcpp2 -Ed)
struct ns__applyFilterResponse
{
/// Element "imageData" of type xs:base64Binary.
    struct xsd__base64Binary             imageData                      1;	///< Required element.
/// Element "processingTime" of type xs:int.
    int                                  processingTime                 1;	///< Required element.
};

/// @brief "http://tempuri.org/ns.xsd":serverInfoResponse is a complexType.
///
/// @note struct ns__serverInfoResponse operations:
/// - ns__serverInfoResponse* soap_new_ns__serverInfoResponse(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default_ns__serverInfoResponse(struct soap*, ns__serverInfoResponse*) default initialize members
/// - int soap_read_ns__serverInfoResponse(struct soap*, ns__serverInfoResponse*) deserialize from a source
/// - int soap_write_ns__serverInfoResponse(struct soap*, ns__serverInfoResponse*) serialize to a sink
/// - ns__serverInfoResponse* soap_dup_ns__serverInfoResponse(struct soap*, ns__serverInfoResponse* dst, ns__serverInfoResponse *src) returns deep copy of ns__serverInfoResponse src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del_ns__serverInfoResponse(ns__serverInfoResponse*) deep deletes ns__serverInfoResponse data members, use only on dst after soap_dup_ns__serverInfoResponse(NULL, ns__serverInfoResponse *dst, ns__serverInfoResponse *src) (use soapcpp2 -Ed)
struct ns__serverInfoResponse
{
/// Element "clients" of type xs:int.
    int                                  clients                        1;	///< Required element.
/// Element "activeJobs" of type xs:int.
    int                                  activeJobs                     1;	///< Required element.
/// Element "uptime" of type xs:string.
    char*                                uptime                         0;	///< Optional element.
/// Element "memory" of type xs:string.
    char*                                memory                         0;	///< Optional element.
/// Element "queueSize" of type xs:int.
    int                                  queueSize                      1;	///< Required element.
};

/// @brief Top-level root element "http://tempuri.org/ns.xsd":connect
/// @brief "http://tempuri.org/ns.xsd":connect is a complexType.
///
/// @note struct _ns__connect operations:
/// - _ns__connect* soap_new__ns__connect(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default__ns__connect(struct soap*, _ns__connect*) default initialize members
/// - int soap_read__ns__connect(struct soap*, _ns__connect*) deserialize from a source
/// - int soap_write__ns__connect(struct soap*, _ns__connect*) serialize to a sink
/// - _ns__connect* soap_dup__ns__connect(struct soap*, _ns__connect* dst, _ns__connect *src) returns deep copy of _ns__connect src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del__ns__connect(_ns__connect*) deep deletes _ns__connect data members, use only on dst after soap_dup__ns__connect(NULL, _ns__connect *dst, _ns__connect *src) (use soapcpp2 -Ed)
struct _ns__connect
{
};

/// @brief Top-level root element "http://tempuri.org/ns.xsd":connectResponse
/// @brief "http://tempuri.org/ns.xsd":connectResponse is a complexType.
///
/// @note struct _ns__connectResponse operations:
/// - _ns__connectResponse* soap_new__ns__connectResponse(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default__ns__connectResponse(struct soap*, _ns__connectResponse*) default initialize members
/// - int soap_read__ns__connectResponse(struct soap*, _ns__connectResponse*) deserialize from a source
/// - int soap_write__ns__connectResponse(struct soap*, _ns__connectResponse*) serialize to a sink
/// - _ns__connectResponse* soap_dup__ns__connectResponse(struct soap*, _ns__connectResponse* dst, _ns__connectResponse *src) returns deep copy of _ns__connectResponse src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del__ns__connectResponse(_ns__connectResponse*) deep deletes _ns__connectResponse data members, use only on dst after soap_dup__ns__connectResponse(NULL, _ns__connectResponse *dst, _ns__connectResponse *src) (use soapcpp2 -Ed)
struct _ns__connectResponse
{
/// Element "connect" of type xs:int.
    int*                                 connect                        0;	///< Optional element.
};

/// @brief Top-level root element "http://tempuri.org/ns.xsd":echo
/// @brief "http://tempuri.org/ns.xsd":echo is a complexType.
///
/// @note struct _ns__echo operations:
/// - _ns__echo* soap_new__ns__echo(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default__ns__echo(struct soap*, _ns__echo*) default initialize members
/// - int soap_read__ns__echo(struct soap*, _ns__echo*) deserialize from a source
/// - int soap_write__ns__echo(struct soap*, _ns__echo*) serialize to a sink
/// - _ns__echo* soap_dup__ns__echo(struct soap*, _ns__echo* dst, _ns__echo *src) returns deep copy of _ns__echo src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del__ns__echo(_ns__echo*) deep deletes _ns__echo data members, use only on dst after soap_dup__ns__echo(NULL, _ns__echo *dst, _ns__echo *src) (use soapcpp2 -Ed)
struct _ns__echo
{
/// Element "echoRequest" of type xs:string.
    char*                                echoRequest                    0;	///< Optional element.
};

/// @brief Top-level root element "http://tempuri.org/ns.xsd":echoResponse
/// @brief "http://tempuri.org/ns.xsd":echoResponse is a complexType.
///
/// @note struct _ns__echoResponse operations:
/// - _ns__echoResponse* soap_new__ns__echoResponse(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default__ns__echoResponse(struct soap*, _ns__echoResponse*) default initialize members
/// - int soap_read__ns__echoResponse(struct soap*, _ns__echoResponse*) deserialize from a source
/// - int soap_write__ns__echoResponse(struct soap*, _ns__echoResponse*) serialize to a sink
/// - _ns__echoResponse* soap_dup__ns__echoResponse(struct soap*, _ns__echoResponse* dst, _ns__echoResponse *src) returns deep copy of _ns__echoResponse src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del__ns__echoResponse(_ns__echoResponse*) deep deletes _ns__echoResponse data members, use only on dst after soap_dup__ns__echoResponse(NULL, _ns__echoResponse *dst, _ns__echoResponse *src) (use soapcpp2 -Ed)
struct _ns__echoResponse
{
/// Element "echo" of type xs:string.
    char*                                echo                           0;	///< Optional element.
};

/// @brief Top-level root element "http://tempuri.org/ns.xsd":applyFilter
/// @brief "http://tempuri.org/ns.xsd":applyFilter is a complexType.
///
/// @note struct _ns__applyFilter operations:
/// - _ns__applyFilter* soap_new__ns__applyFilter(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default__ns__applyFilter(struct soap*, _ns__applyFilter*) default initialize members
/// - int soap_read__ns__applyFilter(struct soap*, _ns__applyFilter*) deserialize from a source
/// - int soap_write__ns__applyFilter(struct soap*, _ns__applyFilter*) serialize to a sink
/// - _ns__applyFilter* soap_dup__ns__applyFilter(struct soap*, _ns__applyFilter* dst, _ns__applyFilter *src) returns deep copy of _ns__applyFilter src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del__ns__applyFilter(_ns__applyFilter*) deep deletes _ns__applyFilter data members, use only on dst after soap_dup__ns__applyFilter(NULL, _ns__applyFilter *dst, _ns__applyFilter *src) (use soapcpp2 -Ed)
struct _ns__applyFilter
{
/// Element "imageData" of type xs:base64Binary.
    struct xsd__base64Binary             imageData                      1;	///< Required element.
/// Element "filterType" of type xs:string.
    char*                                filterType                     0;	///< Optional element.
/// Element "processCount" of type xs:int.
    int                                  processCount                   1;	///< Required element.
/// Element "clientId" of type xs:int.
    int*                                 clientId                       0;	///< Optional element.
};

/// @brief Top-level root element "http://tempuri.org/ns.xsd":bye
/// @brief "http://tempuri.org/ns.xsd":bye is a complexType.
///
/// @note struct _ns__bye operations:
/// - _ns__bye* soap_new__ns__bye(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default__ns__bye(struct soap*, _ns__bye*) default initialize members
/// - int soap_read__ns__bye(struct soap*, _ns__bye*) deserialize from a source
/// - int soap_write__ns__bye(struct soap*, _ns__bye*) serialize to a sink
/// - _ns__bye* soap_dup__ns__bye(struct soap*, _ns__bye* dst, _ns__bye *src) returns deep copy of _ns__bye src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del__ns__bye(_ns__bye*) deep deletes _ns__bye data members, use only on dst after soap_dup__ns__bye(NULL, _ns__bye *dst, _ns__bye *src) (use soapcpp2 -Ed)
struct _ns__bye
{
/// Element "byeRequest" of type "http://tempuri.org/ns.xsd":byeRequest.
    struct ns__byeRequest*              byeRequest                     1;	///< Required element.
};

/// @brief Top-level root element "http://tempuri.org/ns.xsd":byeResponse
/// @brief "http://tempuri.org/ns.xsd":byeResponse is a complexType.
///
/// @note struct _ns__byeResponse operations:
/// - _ns__byeResponse* soap_new__ns__byeResponse(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default__ns__byeResponse(struct soap*, _ns__byeResponse*) default initialize members
/// - int soap_read__ns__byeResponse(struct soap*, _ns__byeResponse*) deserialize from a source
/// - int soap_write__ns__byeResponse(struct soap*, _ns__byeResponse*) serialize to a sink
/// - _ns__byeResponse* soap_dup__ns__byeResponse(struct soap*, _ns__byeResponse* dst, _ns__byeResponse *src) returns deep copy of _ns__byeResponse src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del__ns__byeResponse(_ns__byeResponse*) deep deletes _ns__byeResponse data members, use only on dst after soap_dup__ns__byeResponse(NULL, _ns__byeResponse *dst, _ns__byeResponse *src) (use soapcpp2 -Ed)
struct _ns__byeResponse
{
/// Element "status" of type xs:int.
    int*                                 status                         0;	///< Optional element.
};

/// @brief Top-level root element "http://tempuri.org/ns.xsd":serverInfo
/// @brief "http://tempuri.org/ns.xsd":serverInfo is a complexType.
///
/// @note struct _ns__serverInfo operations:
/// - _ns__serverInfo* soap_new__ns__serverInfo(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default__ns__serverInfo(struct soap*, _ns__serverInfo*) default initialize members
/// - int soap_read__ns__serverInfo(struct soap*, _ns__serverInfo*) deserialize from a source
/// - int soap_write__ns__serverInfo(struct soap*, _ns__serverInfo*) serialize to a sink
/// - _ns__serverInfo* soap_dup__ns__serverInfo(struct soap*, _ns__serverInfo* dst, _ns__serverInfo *src) returns deep copy of _ns__serverInfo src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del__ns__serverInfo(_ns__serverInfo*) deep deletes _ns__serverInfo data members, use only on dst after soap_dup__ns__serverInfo(NULL, _ns__serverInfo *dst, _ns__serverInfo *src) (use soapcpp2 -Ed)
struct _ns__serverInfo
{
/// Element "in" of type xs:string.
    char*                                in                             0;	///< Optional element.
};

/// @brief "http://tempuri.org/ns.xsd":connect is a complexType with simpleContent extension of type xs:anyType.
///
/// @note struct ns__connect operations:
/// - ns__connect* soap_new_ns__connect(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default_ns__connect(struct soap*, ns__connect*) default initialize members
/// - int soap_read_ns__connect(struct soap*, ns__connect*) deserialize from a source
/// - int soap_write_ns__connect(struct soap*, ns__connect*) serialize to a sink
/// - ns__connect* soap_dup_ns__connect(struct soap*, ns__connect* dst, ns__connect *src) returns deep copy of ns__connect src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del_ns__connect(ns__connect*) deep deletes ns__connect data members, use only on dst after soap_dup_ns__connect(NULL, ns__connect *dst, ns__connect *src) (use soapcpp2 -Ed)
struct ns__connect
{
/// INHERITED FROM ns__connect:
/// __item wraps simpleContent of type xs:anyType.
    _XML                                 __item                        ;
//  END OF INHERITED FROM ns__connect
};


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://tempuri.org/ns.xsd                                                *
 *                                                                            *
\******************************************************************************/

/// @brief Top-level root element "http://tempuri.org/ns.xsd":applyFilterResponse of type "http://tempuri.org/ns.xsd":applyFilterResponse.
/// @note Use wsdl2h option -g to auto-generate a top-level root element declaration.

/// @brief Top-level root element "http://tempuri.org/ns.xsd":serverInfoResponse of type "http://tempuri.org/ns.xsd":serverInfoResponse.
/// @note Use wsdl2h option -g to auto-generate a top-level root element declaration.


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://tempuri.org/ns.xsd                                                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	pif 
//gsoap ns1  service type:	pifPortType 
//gsoap ns1  service port:	http://localhost:18082 
//gsoap ns1  service namespace:	http://tempuri.org/ns.xsd 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage pif Definitions

@section pif_bindings Service Bindings

  - @ref pif

@section pif_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/** @page pif Binding "pif"

@section pif_service Service Documentation "pif"
gSOAP 2.8.91 generated service definition

@section pif_operations Operations of Binding "pif"

  - @ref __ns__connect

  - @ref __ns__echo

  - @ref __ns__applyFilter

  - @ref __ns__bye

  - @ref __ns__serverInfo

@section pif_ports Default endpoints of Binding "pif"

  - http://localhost:18082

@note Use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   pif                                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns__connect                                                           *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns__connect" of service binding "pif".
Service definition of function ns__connect

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://localhost:18082

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns__connect(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    struct _ns__connect*               ns__connect,
    // output parameters:
    struct _ns__connectResponse       *ns__connectResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns__connect(
    struct soap *soap,
    // input parameters:
    struct _ns__connect*               ns__connect,
    // output parameters:
    struct _ns__connectResponse       *ns__connectResponse
  );
@endcode

*/

//gsoap ns1  service method-protocol:	connect SOAP
//gsoap ns1  service method-style:	connect document
//gsoap ns1  service method-encoding:	connect literal
//gsoap ns1  service method-action:	connect ""
//gsoap ns1  service method-output-action:	connect Response
int __ns__connect(
    struct _ns__connect*               ns__connect,	///< Input parameter
    struct _ns__connectResponse       *ns__connectResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns__echo                                                              *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns__echo" of service binding "pif".
Service definition of function ns__echo

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://localhost:18082

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns__echo(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    struct _ns__echo*                  ns__echo,
    // output parameters:
    struct _ns__echoResponse          *ns__echoResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns__echo(
    struct soap *soap,
    // input parameters:
    struct _ns__echo*                  ns__echo,
    // output parameters:
    struct _ns__echoResponse          *ns__echoResponse
  );
@endcode

*/

//gsoap ns1  service method-protocol:	echo SOAP
//gsoap ns1  service method-style:	echo document
//gsoap ns1  service method-encoding:	echo literal
//gsoap ns1  service method-action:	echo ""
//gsoap ns1  service method-output-action:	echo Response
int __ns__echo(
    struct _ns__echo*                  ns__echo,	///< Input parameter
    struct _ns__echoResponse          *ns__echoResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns__applyFilter                                                       *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns__applyFilter" of service binding "pif".
Service definition of function ns__applyFilter

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://localhost:18082

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns__applyFilter(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    struct _ns__applyFilter*           ns__applyFilter,
    // output parameters:
    struct ns__applyFilterResponse    *ns__applyFilterResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns__applyFilter(
    struct soap *soap,
    // input parameters:
    struct _ns__applyFilter*           ns__applyFilter,
    // output parameters:
    struct ns__applyFilterResponse    *ns__applyFilterResponse
  );
@endcode

*/

//gsoap ns1  service method-protocol:	applyFilter SOAP
//gsoap ns1  service method-style:	applyFilter document
//gsoap ns1  service method-encoding:	applyFilter literal
//gsoap ns1  service method-action:	applyFilter ""
//gsoap ns1  service method-output-action:	applyFilter Response
int __ns__applyFilter(
    struct _ns__applyFilter*           ns__applyFilter,	///< Input parameter
    struct ns__applyFilterResponse    *ns__applyFilterResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns__bye                                                               *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns__bye" of service binding "pif".
Service definition of function ns__bye

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://localhost:18082

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns__bye(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    struct _ns__bye*                   ns__bye,
    // output parameters:
    struct _ns__byeResponse           *ns__byeResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns__bye(
    struct soap *soap,
    // input parameters:
    struct _ns__bye*                   ns__bye,
    // output parameters:
    struct _ns__byeResponse           *ns__byeResponse
  );
@endcode

*/

//gsoap ns1  service method-protocol:	bye SOAP
//gsoap ns1  service method-style:	bye document
//gsoap ns1  service method-encoding:	bye literal
//gsoap ns1  service method-action:	bye ""
//gsoap ns1  service method-output-action:	bye Response
int __ns__bye(
    struct _ns__bye*                   ns__bye,	///< Input parameter
    struct _ns__byeResponse           *ns__byeResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns__serverInfo                                                        *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns__serverInfo" of service binding "pif".
Service definition of function ns__serverInfo

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://localhost:18082

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns__serverInfo(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    struct _ns__serverInfo*            ns__serverInfo,
    // output parameters:
    struct ns__serverInfoResponse     *ns__serverInfoResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns__serverInfo(
    struct soap *soap,
    // input parameters:
    struct _ns__serverInfo*            ns__serverInfo,
    // output parameters:
    struct ns__serverInfoResponse     *ns__serverInfoResponse
  );
@endcode

*/

//gsoap ns1  service method-protocol:	serverInfo SOAP
//gsoap ns1  service method-style:	serverInfo document
//gsoap ns1  service method-encoding:	serverInfo literal
//gsoap ns1  service method-action:	serverInfo ""
//gsoap ns1  service method-output-action:	serverInfo Response
int __ns__serverInfo(
    struct _ns__serverInfo*            ns__serverInfo,	///< Input parameter
    struct ns__serverInfoResponse     *ns__serverInfoResponse	///< Output parameter
);

/** @page pif Binding "pif"

@section pif_policy_enablers Policy Enablers of Binding "pif"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/** @page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings that are contractually bound by WSDLs and
are auto-generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data
bindings are adopted from XML schemas as part of the WSDL types section or when
running wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

@note The following readers and writers are C/C++ data type (de)serializers
auto-generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

@note Data can be read and deserialized from:
  - an int file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = (int)...
  - a C++ stream (istream, stringstream), using soap->is = (istream*)...
  - a C string, using soap->is = (const char*)...
  - any input, using the soap->frecv() callback

@note Data can be serialized and written to:
  - an int file descriptor, using soap->sendfd = (int)...
  - a socket, using soap->socket = (int)...
  - a C++ stream (ostream, stringstream), using soap->os = (ostream*)...
  - a C string, using soap->os = (const char**)...
  - any output, using the soap->fsend() callback

@note The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_set_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_set_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


*/

/**

@section ns1 Top-level root elements of schema "http://tempuri.org/ns.xsd"

  - <ns1:connect> @ref _ns__connect
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns__connect(struct soap*, struct _ns__connect*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns__connect(struct soap*, struct _ns__connect*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns__connect(struct soap*, const char *URL, struct _ns__connect*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns__connect(struct soap*, const char *URL, struct _ns__connect*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns__connect(struct soap*, const char *URL, struct _ns__connect*);
    soap_POST_recv__ns__connect(struct soap*, struct _ns__connect*);
    @endcode

  - <ns1:connectResponse> @ref _ns__connectResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns__connectResponse(struct soap*, struct _ns__connectResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns__connectResponse(struct soap*, struct _ns__connectResponse*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns__connectResponse(struct soap*, const char *URL, struct _ns__connectResponse*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns__connectResponse(struct soap*, const char *URL, struct _ns__connectResponse*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns__connectResponse(struct soap*, const char *URL, struct _ns__connectResponse*);
    soap_POST_recv__ns__connectResponse(struct soap*, struct _ns__connectResponse*);
    @endcode

  - <ns1:echo> @ref _ns__echo
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns__echo(struct soap*, struct _ns__echo*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns__echo(struct soap*, struct _ns__echo*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns__echo(struct soap*, const char *URL, struct _ns__echo*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns__echo(struct soap*, const char *URL, struct _ns__echo*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns__echo(struct soap*, const char *URL, struct _ns__echo*);
    soap_POST_recv__ns__echo(struct soap*, struct _ns__echo*);
    @endcode

  - <ns1:echoResponse> @ref _ns__echoResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns__echoResponse(struct soap*, struct _ns__echoResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns__echoResponse(struct soap*, struct _ns__echoResponse*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns__echoResponse(struct soap*, const char *URL, struct _ns__echoResponse*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns__echoResponse(struct soap*, const char *URL, struct _ns__echoResponse*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns__echoResponse(struct soap*, const char *URL, struct _ns__echoResponse*);
    soap_POST_recv__ns__echoResponse(struct soap*, struct _ns__echoResponse*);
    @endcode

  - <ns1:applyFilter> @ref _ns__applyFilter
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns__applyFilter(struct soap*, struct _ns__applyFilter*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns__applyFilter(struct soap*, struct _ns__applyFilter*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns__applyFilter(struct soap*, const char *URL, struct _ns__applyFilter*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns__applyFilter(struct soap*, const char *URL, struct _ns__applyFilter*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns__applyFilter(struct soap*, const char *URL, struct _ns__applyFilter*);
    soap_POST_recv__ns__applyFilter(struct soap*, struct _ns__applyFilter*);
    @endcode

  - <ns1:applyFilterResponse> (use wsdl2h option -g to auto-generate type _ns__applyFilterResponse)

  - <ns1:bye> @ref _ns__bye
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns__bye(struct soap*, struct _ns__bye*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns__bye(struct soap*, struct _ns__bye*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns__bye(struct soap*, const char *URL, struct _ns__bye*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns__bye(struct soap*, const char *URL, struct _ns__bye*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns__bye(struct soap*, const char *URL, struct _ns__bye*);
    soap_POST_recv__ns__bye(struct soap*, struct _ns__bye*);
    @endcode

  - <ns1:byeResponse> @ref _ns__byeResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns__byeResponse(struct soap*, struct _ns__byeResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns__byeResponse(struct soap*, struct _ns__byeResponse*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns__byeResponse(struct soap*, const char *URL, struct _ns__byeResponse*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns__byeResponse(struct soap*, const char *URL, struct _ns__byeResponse*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns__byeResponse(struct soap*, const char *URL, struct _ns__byeResponse*);
    soap_POST_recv__ns__byeResponse(struct soap*, struct _ns__byeResponse*);
    @endcode

  - <ns1:serverInfo> @ref _ns__serverInfo
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns__serverInfo(struct soap*, struct _ns__serverInfo*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns__serverInfo(struct soap*, struct _ns__serverInfo*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns__serverInfo(struct soap*, const char *URL, struct _ns__serverInfo*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns__serverInfo(struct soap*, const char *URL, struct _ns__serverInfo*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns__serverInfo(struct soap*, const char *URL, struct _ns__serverInfo*);
    soap_POST_recv__ns__serverInfo(struct soap*, struct _ns__serverInfo*);
    @endcode

  - <ns1:serverInfoResponse> (use wsdl2h option -g to auto-generate type _ns__serverInfoResponse)

*/

/* End of pif.h */
